/**
 * Erros Codes
 * Patern: ENTITY_REASON_DETAIL
 */

export const AppErrorCode = {
  // --- AUTH & USER ERRORS ---
  AUTH_UNAUTHORIZED : 'AUTH_UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS : 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN : 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED : 'AUTH_TOKEN_EXPIRED',
  USER_NOT_FOUND : 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS : 'USER_EMAIL_ALREADY_EXISTS', // Prisma P2002 (email)
  USER_ACCOUNT_INACTIVE : 'USER_ACCOUNT_INACTIVE',
  USER_ALREADY_VERIFIED : 'USER_ALREADY_VERIFIED',

  // --- SYSTEM & INFRASTRUCTURE ERRORS ---
  DB_RECORD_NOT_FOUND : 'DB_RECORD_NOT_FOUND', // Prisma P2025
  DB_FOREIGN_KEY_VIOLATION : 'DB_FOREIGN_KEY_VIOLATION', // Prisma P2003
  DB_UNIQUE_CONSTRAINT_VIOLATION : 'DB_UNIQUE_CONSTRAINT_VIOLATION', // Prisma P2002

  // ---GENERIC ERRORS ----
  VALIDATION_ERROR : 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND : 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR : 'INTERNAL_SERVER_ERROR',
  TOO_MANY_REQUESTS : 'TOO_MANY_REQUESTS',
  UPLOAD_FAILED : 'UPLOAD_FAILED',
}  as const

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];
